### PR TITLE
Linux support

### PR DESCRIPTION
**Pull request by renerocksai**
This is almost ready to play but still WIP.

Issues I found

- unrelated: zap's zon version "0.0.10-pre" causes a segfault when printing/writing it
- so I tested in the ezpkg repo, with ezpkg eggzon=../eggzon:
    - when I touch eggzon/me
    - ezpkg enters an infinite update loop

apart from that, it's looking good :smile:

### CODE REVIEW

**Comment by renerocksai** [comment]
hey @mattnite! this is ready for merging. 

I fixed the initial infinite update problem. Turns out my inotify flags were triggering notifications on every file open as well. So some manual file change would trigger the "update" where you'd calculate the new package hash by calculating hashes of all files, opening them in the process -> a notification for each file in the next loop iteration.

It works now. At least the inotify on Linux. Unfortunately, with zap's "0.1.0-pre" zon version, it crashes while trying to write the version, so I only tested it with ezpkg & eggzon.

**Comment by renerocksai** [comment]
Good you haven't merged yet. The past few patches got rid of the `.c` and `.h` files, so now it's only `.zig`.

**Comment by renerocksai** [comment]
rename the project to ezpz ;)

**Comment by mattnite** [comment]
Thanks Rene! Soon we'll get windows working here too :)

**Pull request merged**
